name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]  # o 'master', según tu rama

permissions:
  contents: read
  packages: write

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        IMAGE_NAME=$(echo "ghcr.io/${{ github.repository_owner }}/bitcoin-front:latest" | tr '[:upper:]' '[:lower:]')
        docker build -t $IMAGE_NAME .
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Push Docker image
      run: |
        docker push $IMAGE_NAME
