name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]  # o 'master', según tu rama

permissions:
  contents: read
  packages: write

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/front:latest .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/front:latest